# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d0ed25157fc8fd0cd8ac6417ccbf1cec9ffe0a40d3a2f5c7c0d1d47359ccfcafc8be33577fd63e7860ef5806c84a3d8699152a535e88303d5a6769aa640aac0

test:
  secret_key_base: 738caec4503cb44c2dbe0ab53db2be6e20253644dc14b4f47e44e40f797e55547237e26c38ea3e5b63d9b4e4f73128113288559fce83aff9a20c7c7ac33d9a0a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
